version: "3.8"

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:22-bookworm
    volumes:
      - ..:/workspace:cached
      - washwise-node-modules:/workspace/node_modules
    command: sleep infinity
    networks:
      - washwise-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  washwise-node-modules:

networks:
  washwise-network:
    name: washwise-network
    driver: bridge
